### ISSUE TITLE
test workflowの build ros packages jobsで permission deniedエラーが出る

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#106]
テストする前に ros パッケージをビルドする段階で以下のエラーで落ちます。

https://github.com/sbgisen/cube_python_api/runs/6878724058?check_suite_focus=true

**Comment by Tacha-S** [comment]
https://github.com/sbgisen/.github/pull/104 のPRで解決されているはずです。
おそらくRe-runのときにこのPRが取り込まれる前に走っていたGitHub ActionをRe-runしていそうなので、
適当に何かコミットする等で新しくGitHub Action走らせてみるといいと思います。

**Comment by jsupratman13** [comment]
上記の通り行うことでpermission deniedエラーなくなりました。
