### ISSUE TITLE
unmet dependencies inetutils-ping

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#108]
**概要**
Test/Run test ジョブのupgrade apt packagesステップを実行中に以下のエラーで止まる
```bash
The following packages have unmet dependencies:
 inetutils-ping : Conflicts: ping
E: Broken packages
```
**再現手順**
https://github.com/sbgisen/cube_python_api/runs/7173664508?check_suite_focus=true 
**修正しないとどう困るか**
**原因**
**修正案**

**Comment by Tacha-S** [comment]
aptにinetutils-pingとiputils-pingという少し機能差のあるpingが存在しそれらが干渉し起きるエラーです。
暫定的な対処としてinetutils-pingを消してupgradeできるようにしました。

**Comment by Tacha-S** [comment]
こちらで対応します。
https://github.com/sbgisen/docker_ws/issues/19
