### ISSUE TITLE
melodicのサポートをどう残すか

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#121]
**概要**

linterに関してもnoetic移行で使える記法を用いると引っかかることがある。
https://github.com/sbgisen/cube_experimental_smach/pull/4#discussion_r987591006

これはlinterがpython2で動作しているためであり、
修正対応はすぐにできるがmelodicのCIが必要な場合にそちらが通らなくなる恐れがある。

buildやtestのようにmelodicで走らせるかnoeticで走らせるかを引数で与えるようにする(サポートし続ける)か
melodicのCIはここらへんでブランチを切って`main`ではなくそのブランチを指定してもらうようにする(基本的に`main`での改善は入れない。bugfixのみ)か

個人的には後者でいいと思っているが、
なにか意見あればください。

**目的**
**提案内容**
**タスク**
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by jsupratman13** [comment]
後者でいいと思います。
