### ISSUE TITLE
rosdepによってpython環境がおかしくなる

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#126]
**概要**

rosdepで[python-is-python2がインストールされる](https://github.com/sbgisen/cube_experimental_smach/actions/runs/3224389072/jobs/5275601725#step:8:10222) ことがあり/usr/bin/pythonのリンク先がpython2になってしまう。

関連
- #115

**再現手順**
**修正しないとどう困るか**
**原因**
**修正案**

どのパッケージの依存で入るか不明なので
rosdep後に強制的にpython-is-python3を入れ直す

**Comment by jsupratman13** [comment]
applied patch on #125 but leaving this issue open for now

**Comment by Tacha-S** [comment]
jsk_recognition_utilsにてcythonを入れてしまうことが原因と判明
cython3にするようにhttps://github.com/sbgisen/jsk_recognition/tree/feature/athome にて対応
https://github.com/sbgisen/cube_experimental_smach/actions/runs/3317952497 にてCI動作確認
