### ISSUE TITLE
cmakeのフォーマットチェックでreviewdogに指摘される箇所がpre-commitでは指摘されない

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/.github#155]
**概要**

reviewdogでコメントのフォーマットについて指摘されたが、現在の.cmake-formatの設定では、pre-commit時に引っかからない模様

https://github.com/sbgisen/cube/pull/827#discussion_r1096954577

**Comment by Tacha-S** [comment]
autopep8も同様なことがたまに見られ、autopep8に関してはpre-commit側のversionの更新が遅れていることに起因していそうですが、cmake-formatは他の要因がありそうです。

**Comment by Tacha-S** [comment]
自分の環境で該当コミットまで遡ってコミットしましたが検出できているので.cmake-formatがrootまでの道中に置かれているか、cmake-formatのversionが0.6.13かあたりを確認するのが良さそうです。
```bash
cmake-format.............................................................Failed
- hook id: cmake-format
- files were modified by this hook
```

**Comment by MikhailBertrand** [comment]
すみません、これ調べたら自分のVSCodeのsettings.jsonで誤った`"cmakeFormat.args"`が指定されているだけでした（この間誤ってsettings.jsonを昔のものに戻してしまった）。正しいものにしたところ検出できました。
