### ISSUE TITLE
test時にサーバにあるレポジトリと.rosinstallに書かれているレポジトリのリモートが異なる時

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#185]
**概要**
vcs importは レポジトリ名が同じでもリモートが違うと別レポジトリ扱いとする．両方扱いしたいならvsc的にclone先のディレクトリ名をユニークにすれば大丈夫らしいが，ROS的に同じパッケージ名が２つあると問題．git remote使うとことで一つレポジトリで異なるリモートを切り替えることが出来るが，vcsは切り替えを対応していない．

何かいい方法はあるかな？

**目的**
**提案内容**
**タスク**
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by Tacha-S** [comment]
`--force` の挙動を調べた感じではそのディレクトリに同一のremote repositoryが登録されていれば削除せず、
もし全く別のよくわからないものが置かれていたときだけ削除してpullしていそうなのでこのオプションを追加するのが良さそうです。
