### ISSUE TITLE
pythonのformatter, linterをruffで置き換える？

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#187]
**概要**

isortとほぼ互換性のあるimport sortと、flake8ともほぼ互換性のあるlinter機能を兼ね備える[ruff](https://github.com/astral-sh/ruff)に
formatterの機能が追加(blackと互換性があり, autopep8との違いはE203まわりとたまに改行位置が変わることもありそう)されたので
乗り換えたほうが楽かもしれない

**目的**
**提案内容**
**タスク**
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by MikhailBertrand** [comment]
#216 のときに見逃していたのですが、linterをruffに統一するのであればautopep8とyapfはpyproject.tomlから外しませんか？

https://github.com/sbgisen/.github/blob/f0a71585dbe5f1f511234c95d53d1e45afc1266c/pyproject.toml#L6-L13

- 複数のフォーマッターが存在しているのがややこしく、設定が干渉しうるので恐らく不適切
- yapfが括弧に関連した各種インデントについてやたらと必要性を感じない修正を押し付けてくる（設定を変えれば調整できそうではあるが）

というのが理由です。

**Comment by Tacha-S** [comment]
まず、linerとformatterは別物であることを理解していただかないと話が始まりません。

そのうえで、
まずautopep8の設定をなくすかどうかですが、これについては消しても構わないです。
意図的に動作させなければ発動しないので設定が干渉することはないですが...

次に、yapfからruffのformatterに変えるとするのであれば、
可読性を下げるという主観的評価ではなく、以下の論点を打破しうる主張をしてください。
(こだわりはないので、主観的評価を過半数以上同意を得てくるでもいいですが、少なくとも以下の点については説明した上での同意を得てきてほしいです。)

> ではblackに乗り換えようとなったときに生じる問題が、
公式ではWe pick single quotes over double quotes as long as no escaping is necessary.([参照](https://docs.ros.org/en/jazzy/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#id4))となっているところ。
blackはdouble quotesを採用するので不適切。
ではblackと同等のスタイルを目指しつつsingle quotes, double quotesを設定で変えられるruffはどうかというと、
[E203](https://www.flake8rules.com/rules/E203.html)を無視するため不適切。
そのため、autopep8やyapfにて整形という形になりそう。

https://sbgisen.docbase.io/posts/3561109


あとruffの設定でformatを調整しようというのは、ruffはblackと同等のformatになることを目指していたはずなのでおそらく無理な話です。

**Comment by MikhailBertrand** [comment]
昨日このコメントした後調べて「あー置き換えは無理なんだなー」と理解したのでご放念ください。yapf知らなかったのでLinter機能がないということも認識していなかったです。

（最初AIに「いやtomlに複数のLinterツール設定混ぜるの良くないよ」みたいなこと言われたので…でもこれも僕の認識間違いだったので…）

**Comment by MikhailBertrand** [comment]
> 可読性を下げるという主観的評価ではなく

ちなみにですが、僕が気になったのは関数の引数を羅列する場合などであえて見やすいように改行して左側に寄せている部分を、右端に寄せていって読みづらくフォーマットされてしまう点で、完全に僕の主観です。皆さん的には多分気にならないです。

これが
```python
result = my_function(
    first_arg,
    second_arg,
    third_arg
)
```
これに整形されてしまうのでどんどん右端にコードが寄ってしまって私的にはかなり苦手だったので
```python
result = my_function(first_arg,
                     second_arg,
                     third_arg)
```
以下のように`split_before_first_argument `を`true`にしたいのですが、そうする逆に皆さん使いがちな上の後者の例が弾かれてしまうようなので諦めました。
```
[tool.yapf]
based_on_style = "google"
column_limit = 119
indent_width = 4
split_before_first_argument = true
```

**Comment by Tacha-S** [comment]
```python
result = my_function(
    first_arg,
    second_arg,
    third_arg
)
```

最終項のあとにコンマを置くことを拒絶しないなら、
以下のようにコンマを入れるとフォーマットかけても維持されると思います。
```python
result = my_function(
    first_arg,
    second_arg,
    third_arg,
)
```

> このissueってもう結論出て対応済みみたいなのでcloseしても問題ありませんか？

大丈夫です。
