### ISSUE TITLE
cube-webapps用のnpmのBuild/TestのActionを選定したい

### ISSUE THREAD

**Issue by h-wata** [sbgisen/.github#20]
**概要**
cube-webappのテストを作成していただいているがCIで走らせられて居ないので追加したい。
**目的**
レビューの効率化のため

**提案内容**
**タスク**
- [ ] 良さそうなActionの選定
- [ ] Actionの追加

**Comment by Tacha-S** [comment]
このIssueはwebapp側 https://github.com/sbgisen/cube-webapp/pull/284 で解決したということでいいですか？

**Comment by h-wata** [comment]
そうですね。Closeします。
