### ISSUE TITLE
no such option --break-system-packages

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#223]
**概要**

https://github.com/sbgisen/.github/pull/222 を導入したけど、OSのバージョンによって --break-system-packagesが無いエラーが出る

set up jobs項目の Operating system見ると
失敗
https://github.com/sbgisen/fra/actions/runs/11379642957/job/31657598344?pr=24
Ubuntu 22.04.5

成功:
https://github.com/sbgisen/point_head/actions/runs/11359817795/job/31596527316?pr=22
Ubuntu 24.04.1

**再現手順**
**修正しないとどう困るか**
**原因**
**修正案**

**Comment by Tacha-S** [comment]
https://github.com/sbgisen/.github/blob/1049976b182f9ac22015b470ecd2d3dac5752c59/.github/workflows/ros2_style.yaml#L95-L98

この辺と同様にpythonの仮想環境セットアップしてしまうことで`--break-system-packages` をつける必要なくなるのでそうしたほうが良さそうですね。
これこっちで対応したほうがいいですか？

**Comment by jsupratman13** [comment]
おねがいします :bow:
