### ISSUE TITLE
coding utf-8 needed?

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#228]
**概要**
python2 の時必要だったけど、python3はデフォルトで utf-8になっている
付けてる・付けてないコードが混ざっているので、どっちに統一した方がいいのかもしくは統一しなくてもいいかの質問。

```python
# -*- coding:utf-8 -*-
```

**目的**
**提案内容**
**タスク**
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by Tacha-S** [comment]
https://github.com/sbgisen/.github/pull/210

**Comment by jsupratman13** [comment]
なるほどね、付けてる・付けてないコードが混ざってもいい方針ですね。
