### ISSUE TITLE
`typing`だけ`force_single_line`から除外されたままで問題ないか？

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/.github#234]
**概要**

#216 導入に関連しての質問

これまで、Pythonでのimport時は基本的に1行ごとに分けて書いていたが、GoogleのPythonスタイルガイドにはimportする際の分け方についてはルールがなさそうで、現状コミット時に1行importと複数行importがどちらも許される状態となっている。

https://google.github.io/styleguide/pyguide.html#23-packages

統一しようと思えばpyproject.tomlに`force_single_line = true`を書き加えれば統一可能。
```
[tool.isort]
profile = "google"
line_length = 119
known_third_party = ["launch"]
force_single_line = true
```

ただしその場合も`typing`についてのみは無理やり1行にまとめられてしまう模様であり、スタイルガイドを読むと、`typing`に関する言及はあったものの、それを1行importに強制させる言及はなかった。isortがそうなっている模様。
https://google.github.io/styleguide/pyguide.html#31912-imports-for-typing

![image](https://github.com/user-attachments/assets/e6761e12-69b2-45d4-8f43-0af78ed4bc98)

@Tacha-S @jsupratman13 
これについてのルールはあったほうが良いですか？
スタイルガイドに書いていないので共存していても良いですか？

**Comment by jsupratman13** [comment]
あれこれについてルール決まったのでは？

https://github.com/sbgisen/.github/pull/216#issuecomment-2406458748

**Comment by Tacha-S** [comment]
一応 https://google.github.io/styleguide/pyguide.html#313-imports-formatting に記載されていて、
typingとcollections.abcは例外のようです。
isortのgoogle profileもforce_single_lineはTrueにしているので、
わざわざforce_single_lineを明示する必要はないと思いますが、
single_line_exclusionsはtypingのみの模様です。
https://pycqa.github.io/isort/docs/configuration/profiles.html

つまり基本は1行につき1つずつのこれまでのルールは変わらずでいいと思いますが、
typingやabcについてなにか要望があればここでなにか決めてもいいと思います。

**Comment by MikhailBertrand** [comment]
> isortのgoogle profileもforce_single_lineはTrueにしているので、
わざわざforce_single_lineを明示する必要はないと思いますが、

あれ？でもやっぱり明示してあげないとコミット通っちゃうんでけどなんでだろ・・・。

**Comment by MikhailBertrand** [comment]
すみません、何が悪さをしていたのかしりませんが、キャッシュクリアしてコミットし直したらちゃんと弾かれているみたいなので改行については問題なさそうです。

**Comment by MikhailBertrand** [comment]
@Tacha-S 
明確な根拠がパっと見当たらなかったのですが、google profileはなんでデフォルトで`typing`だけ`force_single_line`から除外しているかってわかりますか？

だいたいこんな理由ですか？
<img width="496" alt="image" src="https://github.com/user-attachments/assets/8b7525c7-f175-4619-a54a-6120cd26837a" />

**Comment by jsupratman13** [comment]
https://google.github.io/styleguide/pyguide.html#31912-imports-for-typing

> This keeps common annotations more concise and matches typing practices used around the world.

ここに書いてるのでは。

**Comment by MikhailBertrand** [comment]
なるほどねー。割とクリアか

- 型アノテーションを簡潔に保つため
- Pythonコミュニティの標準的な慣習に一致させるため
- 名前空間の整理や静的解析を容易にするため

**Comment by MikhailBertrand** [comment]
じゃあtypingは例外のままでいいか

**Comment by Tacha-S** [comment]
そのあたりのようですね

**Comment by MikhailBertrand** [comment]
isortのデフォルトの設定いじる必要なさそうなのでcloseします
