### ISSUE TITLE
push時のlint_after_buildでエラーが生じる（lint_after_buildは不要？）

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/.github#44]
**概要**
cubeリポジトリやcube_demosリポジトリで、`lint_after_build`内`changed-file-filter`が失敗する

https://github.com/sbgisen/cube/runs/4532248885?check_suite_focus=true

**修正案**

push時には`lint_after_build`を走らせない

https://github.com/sbgisen/.github/blob/e799ce99e6ff4c47f7e3c12f2f7ec558757e4f92/.github/workflows/ros-test.yml#L98

**Comment by Tacha-S** [comment]
`if: ${{ github.event_name == 'pull_request' }}` をlint_after_buildに入れるで行けると思います。

**Comment by MikhailBertrand** [comment]
大項目（linter・build・test・release_drafter）についてはros-ci.yml内で`github.event_name`判別しているので、lint_after_buildのみtest項目内のworkflow定義で判別を行うのは若干気持ち悪いですが、現状それが良さそうなのでそれでいきます。

**Comment by Tacha-S** [comment]
そうですね。lint_after_buildをlinterのworkflowに入れられれば一番良かったんですが、別のworkflowの結果を受けてから動かすのがぱっと試してた感じできなかったのでその辺そのうち上手くできるようになるといいですね。
