### ISSUE TITLE
import を整理することについて

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#50]
PR #49 でマージした結果以下の書き方ができなくなりました。個人的に前の書き方の方が見やすいと思いますので自動整理不可能であればisort使わずにこちらで整理した方がいいと思いますががいかがでしょうか？

通らない（前の書き方）
```python
from geometry_msgs.msg import Pose, PoseStamped
from geometry_msgs.msg import Point
from geometry_msgs.msg import Quaternion
from geometry_msgs.msg import Vector3                                                                                                                                                                       
from geometry_msgs.msg import Transform, TransformStamped
from move_base_msgs.msg import MoveBaseGoal
```

通る（isortをかけた後）
```python
from geometry_msgs.msg import Point, Pose, PoseStamped, Quaternion, Transform, TransformStamped, Vector3
from move_base_msgs.msg import MoveBaseGoal
```

**Comment by Tacha-S** [comment]
isortのconfigでは同一パス内のものをimportしているときにgroupingを強制しない設定はなかったです。
flake8-import-orderではその辺りはゆるくもう少し自由に書けます。
[例](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_google.py)

よって、
1. isortのsortingに慣れる
2. flake8-import-orderにしてwarning出ているところは手動でsortingする
のどちらかになります。

**Comment by Tacha-S** [comment]
@sbgisen/developer 自分はflake8-import-orderのほうが強制しすぎないので好きなので変えるのは賛成ですが、皆さん大丈夫ですか？

**Comment by MikhailBertrand** [comment]
行が長くなりすぎるのを避けたい場合もあるのでできれば変えてほしいです。

**Comment by h-wata** [comment]
2.のflake8-import-orderにしてもいいような気がしますが、`isort`コマンドのようなFormatterってありますかね？

※Option外なので少しキモいですが、`isort:skip` というのもあるようです。
https://pypi.org/project/isort/
```
from xyz import (abc,  # isort:skip
                 yo,
                 hey)
```

**Comment by h-wata** [comment]
> 2.のflake8-import-orderにしてもいいような気がしますが、`isort`コマンドのようなFormatterってありますかね？

自己解決しました。isortに渡すときに、` -sl, --force-single-line-imports` のオプション渡せばいいようです。

**Comment by Tacha-S** [comment]
ミーティングでも言いましたし、

> 手動でsortingする

と書いてあるようにないです。
force-single-line-importsは1行に1importしかしないように強制しますよね？
joshuaの例だと
from geometry_msgs.msg import Transform, TransformStamped
も分解する。

isortでは改行が必要になったときのstyleがいくつか選べますが、max-lengthの119を超えない限りは1行に収めようとします。
https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html

またisort:skipは明確な判断基準が作りにくく全てにisort:skipされても止めようがないのでその方法は却下です。

**Comment by jsupratman13** [comment]
結局isortを使う
```python
from geometry_msgs.msg import Transform, TransformStamped
```
```python
from geometry_msgs.msg import Transform
from geometry_msgs.msg import TransformStamped
```
どちらか一つしか選べないのならどちらかに統一するのかな？

**Comment by Tacha-S** [comment]
そこでjoshuaが折れたらじゃあisortこのまま使おうかになるだけなんだけど...

**Comment by h-wata** [comment]
https://github.com/sbgisen/.github/blob/ab8cef326f2f4bb53229539bb515691d3c0740e7/setup.cfg#L11-L12

この下に、下記を追加すれば良さそうでした。
```
force_single_line = True
```

**Comment by h-wata** [comment]
`force-single-line-imports`だと今回の要件が満たされないのは理解しました。

> flake8-import-orderのisortコマンドのようなFormatterってありますかね？

こちらはいかがですかね？

**Comment by Tacha-S** [comment]
> ミーティングでも言いましたし、
 >手動でsortingする
> と書いてあるようにないです。

??????

**Comment by h-wata** [comment]
> > ミーティングでも言いましたし、
> > 手動でsortingする
> > と書いてあるようにないです。
> 
> ??????

すみません。主語がなくて分かりませんでした。無いんですね。

**Comment by Tacha-S** [comment]
いちいち全てに引用つけないと前後のスレッド見れませんか失礼いたしました以後気をつけます

**Comment by h-wata** [comment]
> いちいち全てに引用つけないと前後のスレッド見れませんか失礼いたしました以後気をつけます

こちらこそ、スレッドちゃんと読めていませんでした。すみません。

**Comment by h-wata** [comment]
> 1. isortのsortingに慣れる
> 2. flake8-import-orderにしてwarning出ているところは手動でsortingする

これであれば、2が良いです。

**Comment by nyxrobotics** [comment]
@jsupratman13 

> PR #49 でマージした結果以下の書き方ができなくなりました。個人的に前の書き方の方が見やすいと思いますので自動整理不可能であればisort使わずにこちらで整理した方がいいと思いますががいかがでしょうか？
> 

どのような書き方が「見やすい」かは個人差あると思うのですが、私としては「統一されている方が見やすい」というのは個人差ないと思っています。なのでフォーマットをかけること自体は必要だと思っています。


> 結局isortを使う場合
> 
> ```python
> from geometry_msgs.msg import Transform, TransformStamped
> ```
> 
> ```python
> from geometry_msgs.msg import Transform
> from geometry_msgs.msg import TransformStamped
> ```
> 
> どちらか一つしか選べないのならどちらに統一するのかな？

この2択だとジョシュアさんはどちらにしたいのですか？

**Comment by jsupratman13** [comment]
この2択しかないのなら個人的には以下の方が良いと思います。
```python
from geometry_msgs.msg import Transform
from geometry_msgs.msg import TransformStamped
```

今のところ、上記の書き方以外`isort`を使う異議が無いのでまた何かあれば別のissueを立てます。
もし大丈夫なら`--force-single-line-imports`追加して欲しいです。

多分調べ済みだと思いますが一応isortの[issue](https://github.com/PyCQA/isort/issues/1830)にもありました。

**Comment by jsupratman13** [comment]
一旦issueを閉じます。
