### ISSUE TITLE
`***` imported but unused のエラーがignoreされてる

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#61]
**概要**

flake8のチェックでF401(`***` imported but unused)がignoreされてる。
特にignoreする理由がないのでignoreから外す。
(W503はW504と競合するためignoreする必要がある。)

**目的**

不要なimportのチェックを有効化するため

**Comment by Tacha-S** [comment]
__init__.pyででてたからignoreしてたんですね...
PEP8的には__init__.pyに書いたものは__all__に入れるのが正解らしい(__all__に入れると使ってなくてもエラーは出なくなる)
https://stackoverflow.com/questions/31079047/python-pep8-class-in-init-imported-but-not-used

CI的にはpythonファイルと__init__.pyを別物として正規表現書けば実現可能ではあるけれど、
ローカルでチェックしづらくなるし、煩雑になるので避けたいです。

**Comment by Tacha-S** [comment]
こういう自動生成系もあるにはあるみたいです。
https://github.com/Erotemic/mkinit

**Comment by jsupratman13** [comment]
`__all__`を付けるのはベストだね

**Comment by jsupratman13** [comment]
`# noqa`を付けるのはどうかな？

**Comment by Tacha-S** [comment]
`# noqa`にF401のみを指定できる方法があるならそれでも構わないですが、
そうでないなら`# noqa`をつけるぐらいなら`__all__`を書けばいいような気がするですがどうですか？

**Comment by jsupratman13** [comment]
確かに。`__all__`の方がなんか美しい

**Comment by jsupratman13** [comment]
解決案が出たのでこのissueをcloseします。
