### ISSUE TITLE
OS環境が異なるテストが行えない。

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#64]
**概要**

現状melodic(ubuntu 18.04)しか動かしていないため、
noetic(ubuntu 20.04)のブランチを同時進行でテストしようとするとubuntu 18.04上でテストしようとしてしまうため
両環境が壊れてしまうため、host runnerを18.04, 20.04両方用意する、タグなどでテスト実行先を適切に選ぶ必要がある。

**目的**

サポート環境の拡充

**Comment by MikhailBertrand** [comment]
ROS Noetic on Ubuntu 20.04のテストを走らせようとした場合に、self hosted runnerにて走るtestフローにてUbuntuのバージョンが異なるため、トラブルが発生する。以下のいずれかの対策が必要となる。

1. ROS Noetic関連リポジトリに関しては開発のメインストリームとなるまではtestフローを省略する
2. Self Hosted Runnerにて走らせるサーバー環境をDockerベースのものに変更する

**Comment by Tacha-S** [comment]
cuda&melodic環境は用意したことがあったので、https://github.com/myoung34/docker-github-actions-runner この環境を用意してたdockerに上乗せしてsbgisenのrunnerとして登録することができるところまでは確認しました。(personal access tokenが必要)

![Screenshot from 2022-03-14 17-21-20](https://user-images.githubusercontent.com/13605820/158132598-39b23608-ca0b-4bc5-9ba7-3acf035c1799.png)

**Comment by Tacha-S** [comment]
self hosted serverにdockerでmelodic, noetic環境を試験的に構築しましたが、
- noetic環境ではdiff_drive_controllerがcubeの依存に無いためインストールされない
- `catkin run_tests ...`がmelodicでは`catkin build --verbose --catkin-make-args run_tests -- -i --no-deps --no-status cube` にaliasされているが、noeticでは`catkin run_tests -i --no-deps --no-status cube' to 'catkin test -i --no-deps --no-status cube`にaliasされるようで変更が必要そうでした。
