### ISSUE TITLE
rosinstallの再帰的検索に関する問題

### ISSUE THREAD

**Issue by MikhailBertrand** [sbgisen/.github#66]
**概要**

buildフロー及びtestフローのvcstoolによるcloneのステップにて、再帰的にrosinstallファイルを探すことにより、問題が発生する場合がある。

https://github.com/sbgisen/.github/blob/b068bbed3b9d0c366790a1ca0e96f2e2dbd54046/.github/workflows/ros-build.yml#L51-L62

今回、noeticブランチのテストをするに当たって
- ar_track_alver
- eband_local_planner
の各リポジトリをcubeリポジトリのrosinstallに追加する処置を行ったがこの際に、いずれのリポジトリにも自リポジトリを示すrosinstallファイルがTravis用に用意されており、[テストが失敗する](https://github.com/sbgisen/cube/runs/5534758838?check_suite_focus=true#step:6:264)要因となった。

今回、それぞれフォーク先にてrosinstallファイルを削除することで対策を行ったが、build / testフローの再起処理の際に何かしらの対策が取れるのであれば取りたい。

**Comment by Tacha-S** [comment]
rosinstallの再帰探索部分を実行済みのものを削除ではなく
以下のように実行済みのものをignoreに追加していく方法を取れば入力として`ignore_files`を事前に受け取る形で回避できそうです。
https://github.com/sbgisen/cube_python_api/commit/72c836aedc12fb6158acfda029b3f93b4751036f
