### ISSUE TITLE
bashrcで定義している環境変数をrunnerが読み込んでいない

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/.github#72]
**概要**

bashrcで環境変数を定義していても、それが読み込まれていないためtestを走らせるときなどに環境変数で躓く。

**再現手順**
**修正しないとどう困るか**
**原因**

bashrcを読みに行っていないため

**修正案**
https://github.community/t/self-hosted-not-using-bashrc/18358

**Comment by jsupratman13** [comment]
これはどう？

https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by Tacha-S** [comment]
bashrcを読み込むのではなくCIの環境として環境変数を定義できるようにするということ？
cube_python_apiで見つかったSPEAKERの変数が存在しないことへの解決方法としてはそれ含めいろいろあると思うんだけど、
ここのリポジトリとしてはcube_python_apiに特化したworkflowを置いているわけではないのでもうちょっと視野を広げての解決方法を提示してほしいです。
例えばその方法だと、環境変数をここのworkflowに書くのはどのパッケージにも必要な環境変数のみのはずなのでおかしいし、
呼び出し側で書こうとすると[reusable workflowの制限](https://docs.github.com/ja/actions/using-workflows/reusing-workflows#limitations)に引っかかります。
inputで環境変数を渡せるようにしたいというのであればなしではないですが、その場合こんなフォーマットで渡してこう読み込ませるというところまであると嬉しいです。
