### ISSUE TITLE
noetic環境でのドキュメント生成

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#84]
~~話題通り~~
>現段階でnoetic distro/ubuntu 20.04上のドキュメント生成はまだ未検証なので今回はmelodicの場合ドキュメント生成する・noeticの場合ドキュメント生成しない形で大丈夫でしょうか

>>ではnoetic環境でのドキュメント生成のissue作っておいてください。

_Originally posted by @Tacha-S in https://github.com/sbgisen/.github/pull/83#discussion_r843420485_

#83 で、melodic環境でsphinxを用いてドキュメントを自動生成する jobs を追加しましたが、noetic環境でドキュメント自動生成するjobsは追加していません。

Ubuntu 18.04とUbuntu20.04でインストールされるsphinx機能が異なるためドキュメント生成設定を検証する必要がある。

**Comment by MikhailBertrand** [comment]
上の説明では何のドキュメントの話か分からないのでちゃんと概要を書いてください。

**Comment by jsupratman13** [comment]
> 上の説明では何のドキュメントの話か分からないのでちゃんと概要を書いてください。

申し訳けありません、追加しました。
