### ISSUE TITLE
submoduleは考慮している？

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#90]
ビルドテストする時に、rosinstallに入っているレポジトリのsubmoduleは考慮しているが、元のレポジトリのsubmoduleは考慮していますか？

**Comment by Tacha-S** [comment]
されてないのでcloneの部分にrecursiveのoption追加する必要がありますね。

**Comment by jsupratman13** [comment]
`submodules`のオプションが外されている

https://github.com/actions/checkout/issues/116#issuecomment-567340793

**Comment by Tacha-S** [comment]
https://github.com/actions/checkout/blob/v2/action.yml#L62-L70 ありそうだけどそのコメント本当ですか？

**Comment by jsupratman13** [comment]
このエラーはsubmoduleのオプションが無いと勝手に思ってるけど違うのかな？

https://github.com/sbgisen/private_gazebo_models/runs/6468365221?check_suite_focus=true
