### ISSUE TITLE
pipで依存関係解決

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#91]
rosdepはpipを使ったパッケージをインストールすることができるがpipを先にインストールする必要がある。
ros-build.ymlにpipインストール手順あるが、もっと初めの段階で行うべき

**Comment by Tacha-S** [comment]
python-pipをdependsに書いていないパッケージが悪いと思いますが、どうしてもaptで入れるパッケージの依存でpipで入れるパッケージが入らないのであれば先に持っていきます。

**Comment by jsupratman13** [comment]
> python-pipをdependsに書いていないパッケージが悪いと思いますが、どうしてもaptで入れるパッケージの依存でpipで入れるパッケージが入らないのであれば先に持っていきます。

なるほど、確かにそれが正しいやりかただね。
issueをcloseします。
