### ISSUE TITLE
Test fixture node error

### ISSUE THREAD

**Issue by jsupratman13** [sbgisen/.github#93]
cube_python_apiでテスト走らせた時に以下のエラーが出てきました。何故か基本パッケージのactionlib_tutorialのfibonacci_serverが実行できない
```
 <testsuite errors="0" failures="9" name="unittest.suite.TestSuite" tests="9" time="0.968"><testcase classname="rostest.runner.RosTest" name="testdecorator" time="0.1177"><failure type="AssertionError">Test Fixture Nodes ['fibonacci_server'] failed to launch
```

参考：https://github.com/sbgisen/cube_python_api/runs/6607470829?check_suite_focus=true

**Comment by MikhailBertrand** [comment]
テスト環境をDockerに移行した（#89）影響で、これまではテスト落ちにならなかったcube_python_apiの依存漏れが発覚

修正
https://github.com/sbgisen/cube_python_api/pull/183

**Comment by MikhailBertrand** [comment]
cube_python_api側のトラブルだったのでcloseします。

**Comment by jsupratman13** [comment]
I feel the comment below need to be address before closing this issue.

https://github.com/sbgisen/cube_python_api/pull/183#issuecomment-1139223297

**Comment by MikhailBertrand** [comment]
これまではself-hosted runnerであるサーバー側にあらかじめ`actionlib_tutorials`がインストールされていたのでcube_python_apiのテスト実行時に特に依存が足りなくならなかったが、サーバー上の新規Docker環境でテストを実施するようになったので、ちゃんと`rosdep install`で依存が入らないとテストが通らないようになった。package.xmlに`actionlib_tutorials`を入れておけば`rosdep install`でインストールされるので、上述されたようなテストエラーは発生しなくなる。
このリポジトリとは関係のないトラブルである。

**Comment by jsupratman13** [comment]
解決したためcloseします。
