### ISSUE TITLE
ドキュメント生成のタイミングを変更したい

### ISSUE THREAD

**Issue by anna-ss** [sbgisen/.github#99]
**概要**

cube_python_apiのドキュメント生成に関して出た要望になります。
現在、[ros-build.yml内でsphinxのドキュメント生成を行っている](https://github.com/sbgisen/.github/blob/7740d1828e5ccc8a76721587400916cc35177245/.github/workflows/ros-build.yml#L172-L192)のですが、ドキュメントがアップロードされるタイミングがビルドテスト＝pull requestのレビュー前となってしまうため、レビュー後になるように改修したく思っています。

実現方法について知見をいただけますと幸いです。

**検討内容**

- 案1. ros-build.yml内のドキュメント生成は廃止し、各プロジェクト側で、ROS周りのセットアップ＆ドキュメント生成のジョブを書く
  - [イメージ](https://github.com/sbgisen/cube_python_api/blob/feature/deploy/.github/workflows/s3.yml)
  - ROSのセットアップ周りがros-build.ymlの内容と重複し、メンテンナンスが大変になるため避けたい
- 案2. ros-build.yml内にドキュメント生成のジョブは残すが、実行フラグを引数で設ける。デフォルトはfalseにし、利用側が生成したい場合のみtrueを設定する。
- 案3. [未調査] ros-build.yml内のドキュメント生成は廃止する。ros-build.ymlを実行後の環境を再利用し、各プロジェクトのジョブを実行する方法を調査する。

案2が実現性が高いのですが、案3が可能だと、ビルドテスト用のyamlとドキュメント生成用のyamlが目的別に分離できてより良いように思っています。

**Comment by Tacha-S** [comment]
引数取らずとも
https://github.com/sbgisen/.github/blob/7740d1828e5ccc8a76721587400916cc35177245/.github/workflows/ros-test.yml#L140
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

案3ができるといいです。以前やろうとは思いましたがまだ調査が浅いのでできたら嬉しい。

**Comment by anna-ss** [comment]
案3について、ワークフロー実行後の環境の再利用はできないみたいですが、ワークフロー内のジョブを共通化することはできるみたいです。（Composite Action）
環境の再利用ではないので実行時間はかかってしまいますが、ワークフローファイルの分離という意味では目的を達成できそうです。

参考：https://zenn.dev/tmrekk/articles/5fef57be891040

**Comment by Tacha-S** [comment]
分割目的でComposite Action使うのはありですね
案2でComposite Actionに分割すれば可読性、メンテナンス性向上しつつ、実行時間もbuildの環境再利用する場合とほぼ変わらないと思います

**Comment by anna-ss** [comment]
@Tacha-S 
こちら、feature/composite_actionブランチで対応してみたのですが、pull requestの前に動作確認を行いたく思っています。いつも使用されている方法がありましたら教えていただけますと幸いです。

**Comment by Tacha-S** [comment]
fork先でhttps://github.com/sbgisen/cube_python_api/blob/08ea54bd9f3c51a95a58f469d5420094e625a3ca/.github/workflows/ci.yaml#L15
の`main`の部分を`feature/composite_action`に変えてtriggerをpushにしたり、linterみたいなPR必須であればfork先の中でPR出したりすれば動くと思います。
organizationのsecret使う場合はfork先では動かないと思うのでsbgisenの方で同様のことをしてみるといいと思います。

**Comment by anna-ss** [comment]
composite actionを試してみたのですが、動作確認を経て思ったよりも開発難易度の高さを感じ、一旦案2のgithub.event_nameによる制御だけで実装を行いました。

ただ、今後分割のために使う可能性もあると思うため、実際に使ってみて気がついた箇所を記載します。

- メンテナンスに不便な箇所がある
  - ファイル名がactions/アクション名/action.ymlである必要があり、フォルダ移動が大変
  - .githubのworkflowから、.githubのcomposite actionがそのままでは参照できない
    - 参照先が.githubではなく、呼び出し元のリポジトリ（cube-python-apiなど）になる<br>workflowのように`ファイルパス@ブランチ名`で呼び出したり、.githubをチェックアウトすることで対処ができるが、改修時のテストでブランチ名に気をつける必要が出てしまう
- workflowとは違う箇所がある
  - secretsが使えないため、引数が増える
  - timeout-minutesが使えない
  - runを使う時、shellが必要
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
    - 2021/11まではifが使えなかった（開発中のためか、workflowとの違いについて調べようとすると、新旧の情報が混在する）

**Comment by Tacha-S** [comment]
少し気になったので

> .githubのworkflowから、.githubのcomposite actionがそのままでは参照できない
参照先が.githubではなく、呼び出し元のリポジトリ（cube-python-apiなど）になる
workflowのようにファイルパス@ブランチ名で呼び出したり、.githubをチェックアウトすることで対処ができるが、改修時のテストでブランチ名に気をつける必要が出てしまう

この記事をみるに`sbgisen/.github/action-directory`で呼び出せそうですが情報古いですか？
https://damienaicheh.github.io/github/actions/2021/10/07/reuse-workflows-composite-action-en.html

> secretsが使えないため、引数が増える

reusableまではsecrets使えて、その中でcomposite actionのinputに変えるだけなのでそんなに差はでないと思います。

> timeout-minutesが使えない

composite-action１つにつき１つつけるでもいいと思うのでそこまで影響はないと思います。

> runを使う時、shellが必要

shellの入っていない最小限のdocker imageを使ってるわけでもないのでshellを与えればいいと思います。

**Comment by anna-ss** [comment]
> この記事をみるにsbgisen/.github/action-directoryで呼び出せそうですが

はい、リポジトリ名とバージョンの指定で呼び出すことができます。
バージョン指定が、開発中は各ブランチにして、pull requestの際はmainに戻す必要があるため
pull requestの際のCIに影響することを気にしていました。
ただ、.githubはpull request時にはCIは回していないため、開発者が気をつければそれ以外に問題はなさそうですね。
（CIの件については、今回pull requestを作って気が付きました…

他の箇所については、私が現在のros-build.ymlとdocker imageについて知見がなく
composite actionsの仕様に合わせて内容を変更していいのかわからなかったのもあります。
特に問題なければ、移植しても大丈夫かと思います。

**Comment by Tacha-S** [comment]
> バージョン指定が、開発中は各ブランチにして、pull requestの際はmainに戻す必要があるため
pull requestの際のCIに影響することを気にしていました。

ブランチに気をつけるっていうのはそういうことだったんですね。
このリポジトリにCIを入れる予定は今のところないので開発者が気をつけるで大丈夫だと思います。

> 特に問題なければ、移植しても大丈夫かと思います。

調査ありがとうございました。とりあえず今回のドキュメントのデプロイに関しては案2で進めていただいたもので取り込み今後頃合いを見てcomposite action化しようかなと思います
